src/Entity/Slot.php
<?php
/*
 * This file is part of suresnes-escalade website
 */

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use App\Repository\SlotRepository;
use Stringable;
use LogicException;
use DateTimeInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Slot
 */
#[ORM\Entity(repositoryClass: SlotRepository::class)]
#[ORM\Table(name: 'wp_app_slot')]
class Slot implements Stringable
{
    #[ORM\Column(name: 'id', type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private int $id;

    #[Assert\NotBlank]
    #[ORM\ManyToOne(targetEntity: Season::class, cascade: ['all'], fetch: 'EAGER', inversedBy: 'slots')]
    private ?Season $season = null;

    #[Assert\NotBlank]
    #[ORM\Column(name: 'title', type: Types::STRING, length: 64, nullable: false)]
    private string $title;

    #[ORM\Column(name: 'description', type: Types::STRING, length: 255, nullable: true)]
    private ?string $description = null;

    #[Assert\Range(min: 1, max: 7)]
    #[ORM\Column(name: 'dayOfWeek', type: Types::INTEGER, columnDefinition: 'TINYINT', nullable: false)]
    private int $dayOfWeek;

    #[ORM\Column(name: 'beginTime', type: Types::TIME_MUTABLE, nullable: false)]
    private DateTimeInterface $beginTime;

    #[ORM\Column(name: 'endTime', type: Types::TIME_MUTABLE, nullable: false)]
    private DateTimeInterface $endTime;

    #[ORM\Column(name: 'minBirth', type: Types::DATE_MUTABLE, nullable: true)]
    private ?DateTimeInterface $minBirth = null;

    #[ORM\Column(name: 'maxBirth', type: Types::DATE_MUTABLE, nullable: true)]
    private ?DateTimeInterface $maxBirth = null;

    #[Assert\NotBlank]
    #[ORM\Column(name: 'maxPlaces', type: Types::INTEGER)]
    private int $maxPlaces = 20;

    #[Assert\NotBlank]
    #[ORM\Column(name: 'marginPlaces', type: Types::INTEGER)]
    private int $marginPlaces = 2;

    /**
     * @var Collection<int, Subscription> $subscriptions
     */
    #[ORM\OneToMany(targetEntity: Subscription::class, mappedBy: 'activatedSlot', cascade: ['persist', 'remove'], orphanRemoval: false)]
    #[ORM\OrderBy(['status' => 'DESC', 'firstName' => 'ASC', 'lastName' => 'ASC'])]
    private Collection $subscriptions;

    /**
     * @var Collection<int, Subscription> $waitingSubscriptions
     */
    #[ORM\OneToMany(targetEntity: Subscription::class, mappedBy: 'slot1', cascade: ['persist', 'remove'], orphanRemoval: false)]
    #[ORM\OrderBy(['status' => 'DESC', 'createdAt' => 'ASC'])]
    private Collection $waitingSubscriptions;

    #[ORM\Column(name: 'is_full', type: Types::BOOLEAN)]
    private bool $isFull;

    /**
     * @return array<int, string>
     */
    public static function getDayChoices()
    {
        return [
            1 => 'Lundi',
            2 => 'Mardi',
            3 => 'Mercredi',
            4 => 'Jeudi',
            5 => 'Vendredi',
            6 => 'Samedi',
            7 => 'Dimanche',
        ];
    }

    public function __construct()
    {
        $this->waitingSubscriptions = new ArrayCollection();
        $this->subscriptions = new ArrayCollection();
    }

    public function __toString(): string
    {
        $label = sprintf('%s / %s', $this->season, $this->title);

        if ($this->isFull) {
            $label = '[COMPLET] ' . $label;
        }

        return $label;
    }

    public function getLabel(): string
    {
        $label = $this->title;

        if ($this->isFull) {
            $label = '[COMPLET] ' . $label;
        }

        return $label;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setDayOfWeek(int $dayOfWeek): self
    {
        $this->dayOfWeek = $dayOfWeek;

        return $this;
    }

    public function getDayOfWeek(): int
    {
        return $this->dayOfWeek;
    }

    public function getReadableDayOfWeek(): string
    {
        return match ($this->dayOfWeek) {
            1 => 'Lundi',
            2 => 'Mardi',
            3 => 'Mercredi',
            4 => 'Jeudi',
            5 => 'Vendredi',
            6 => 'Samedi',
            7 => 'Dimanche',
            default => throw new LogicException('Incorrect day number: ' . $this->dayOfWeek),
        };
    }

    public function setBeginTime(DateTimeInterface $beginTime): self
    {
        $this->beginTime = $beginTime;

        return $this;
    }

    public function getBeginTime(): DateTimeInterface
    {
        return $this->beginTime;
    }

    public function setEndTime(DateTimeInterface $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getEndTime(): DateTimeInterface
    {
        return $this->endTime;
    }

    public function setMinBirth(DateTimeInterface $minBirth): self
    {
        $this->minBirth = $minBirth;

        return $this;
    }

    public function getMinBirth(): ?DateTimeInterface
    {
        return $this->minBirth;
    }

    public function setMaxBirth(DateTimeInterface $maxBirth): self
    {
        $this->maxBirth = $maxBirth;

        return $this;
    }

    public function getMaxBirth(): ?DateTimeInterface
    {
        return $this->maxBirth;
    }

    public function setSeason(Season $season = null): self
    {
        $this->season = $season;

        return $this;
    }

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setMaxPlaces(int $maxPlaces): self
    {
        $this->maxPlaces = $maxPlaces;

        return $this;
    }

    public function getMaxPlaces(): int
    {
        return $this->maxPlaces;
    }

    public function setMarginPlaces(int $marginPlaces): self
    {
        $this->marginPlaces = $marginPlaces;

        return $this;
    }

    public function getMarginPlaces(): int
    {
        return $this->marginPlaces;
    }

    public function addSubscription(Subscription $subscription): self
    {
        $this->subscriptions[] = $subscription;

        return $this;
    }

    public function removeSubscription(Subscription $subscription): void
    {
        $this->subscriptions->removeElement($subscription);
    }

    /**
     * @return Collection<int, Subscription>
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function setDescription(?string $description = null): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function addWaitingSubscription(Subscription $waitingSubscription): self
    {
        $this->waitingSubscriptions[] = $waitingSubscription;

        return $this;
    }

    public function removeWaitingSubscription(Subscription $waitingSubscription): void
    {
        $this->waitingSubscriptions->removeElement($waitingSubscription);
    }

    /**
     * @return Collection<int, Subscription>
     */
    public function getWaitingSubscriptions(): Collection
    {
        return $this->waitingSubscriptions;
    }

    public function setIsFull(bool $isFull): self
    {
        $this->isFull = $isFull;

        return $this;
    }

    public function getIsFull(): bool
    {
        return $this->isFull;
    }

    public function getIsFilled(): bool
    {
        return (count($this->subscriptions) >= $this->maxPlaces);
    }
}

src/Controller/SlotController.php
<?php
/*
 * This file is part of suresnes-escalade website
 */

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use App\Repository\SeasonRepository;
use App\Repository\SlotRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Subscription controller.
 */
#[Route(path: '/creneaux')]
class SlotController extends AbstractController
{
    /**
     * Lists all Subscription entities.
     */
    #[Route(path: '/', name: 'slots', methods: ['GET'])]
    public function index(SeasonRepository $seasonRepository): Response
    {
        $season = $seasonRepository->findCurrent();

        return $this->render('slot/index.html.twig', ['season' => $season]);
    }

    /**
     * Lists all Subscription entities.
     */
    #[Route(path: '/inscrits', name: 'slots_subscriptions', methods: ['GET'])]
    #[Route(path: '/details', name: 'slots_details', methods: ['GET'])]
    public function subscriptions(SeasonRepository $seasonRepository, SlotRepository $slotRepository, Request $request): Response
    {
        $season = $seasonRepository->findCurrent();
        $slots = $slotRepository->findForSeason($season);
        $routeName = $request->attributes->get('_route');

        return $this->render('slot/subscriptions.html.twig', [
            'season' => $season,
            'slots' => $slots,
            'full' => $routeName === 'slots_details'
        ]);
    }
}

templates/slot/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Horaires des créneaux {{ season.title|lower }}</h1>

<ul>
	{% for slotType in slotTypes %}
	<li><strong>{{ slotType.title }} :</strong> {{ slotType.description }}</li>
	{% endfor %}
</ul>

<table>
	<thead>
		<tr>
			<th>Jour</th>
			<th>Horaire</th>
			<th>Description</th>
			<th>Type</th>
			<th>Capacité max</th>
		</tr>
	</thead>
	<tbody>
		{% for slot in season.slots %}
		<tr>
			<td>{{ slot.readableDayOfWeek }}</td>
			<td>{{ slot.beginTime|date('H:i') }} à {{ slot.beginTime|date('H:i') }}</td>
			<td>{{ slot.description }}</td>
			<td>{{ slot.type }}</td>
			<td>{{ slot.maxPlaces }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/slot/subscriptions.html.twig
{% import _self as helper %}

{% macro lastname(lastname, full) %}
    <span class="lastname">
	{% if full %}
	    {{ lastname }}
	{% else %}
	    {{ lastname|first }}
	{% endif %}
    </span>
{% endmacro %}

{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{asset('app/css/style.css')}}">
{% endblock %}

{% block body %}
    <h1>Liste des inscrits par créneau /
	{{season.title}}</h1>

    <table class="creneaux-remplissage">
	<thead>
	    <tr>
		<th>
		    <h2>Créneaux</h2>
		</th>
		<th>
		    <h2>Inscrits</h2>
		</th>
	    </tr>
	</thead>
	{% for slot in slots %}
	    <tr data-slot-id="{{slot.id}}">
		<td class="slot">
		    <h3 data-testid="slot-title">{{ slot.title }}</h3>
		    <p>
			<strong>({{ slot.maxPlaces }}
			    personnes maximum)</strong>
		    </p>
		    <p class="description">{{ slot.description|nl2br }}</p>
		</td>
		<td data-testid="slot-subscription" class="subscription">
		    {% if slot.subscriptions|length > 0 %}
			<ol>
			    {% for subscription in slot.subscriptions | filter(subscription => subscription.isActive) %}
				<li>{{ subscription.firstName|capitalize }}
				    {{helper.lastname(subscription.lastName, full)}}
				    {% if not subscription.hasValidCertificate %}
					( Certif
					{{ subscription.getCertifStatusLabel|lower }}
					)
				    {% endif %}
				</li>
			    {% endfor %}
			</ol>
		    {% endif %}

		    {% if slot.waitingSubscriptions| length > 0 %}
			<ul>
			    {% for subscription in slot.waitingSubscriptions | filter(subscription => (subscription.isWaiting or subscription.isPaymentPending or subscription.isWaitingPlace)) %}
				<li class="waiting">{{ subscription.firstName|capitalize }}
				    {{helper.lastname(subscription.lastName, full)}}
				    {% if subscription.hasValidCertificate %}
					(
					{{ subscription.getStatusLabel }}
					)
				    {% else %}
					(
					{{ subscription.getStatusLabel }}, certif
					{{ subscription.getCertifStatusLabel|lower }}
					)
				    {% endif %}
				</li>
			    {% endfor %}
			</ul>
		    {% endif %}
		</td>
	    </tr>
	{% endfor %}
    </table>
{% endblock %}